# Generated by Django 4.1.13 on 2024-06-20 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.CharField(max_length=20, unique=True)),
                ('aprendices_matriculados_ficha', models.IntegerField()),
                ('aprendices_actuales_ficha', models.IntegerField()),
                ('jornada_ficha', models.CharField(choices=[('Diurna', 'Diurna'), ('Tarde', 'Tarde'), ('Nocturna', 'Nocturna')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_programa', models.CharField(max_length=100)),
                ('tipo_formacion_programa', models.CharField(choices=[('Tecnico', 'Tecnico'), ('Tecnologo', 'Tecnologo')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_biometricos_registro', models.ImageField(upload_to='foto_registro')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apellidos_usuario', models.CharField(max_length=50)),
                ('genero_usuario', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20)),
                ('correo_institucional_usuario', models.CharField(max_length=50)),
                ('correo_personal_usuario', models.CharField(max_length=50)),
                ('tipo_documento_usuario', models.CharField(choices=[('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Cedula de ciudadania', 'Cedula de ciudadania'), ('Cedula de extranjeria', 'Cedula de extranjeria')], max_length=50)),
                ('numero_documento_usuario', models.CharField(max_length=20, unique=True)),
                ('rol_usuario', models.CharField(choices=[('Administrador', 'Administrador'), ('Guardia', 'Guardia'), ('Instructor', 'Instructor'), ('Aprendiz', 'Aprendiz')], max_length=13)),
                ('ficha_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.ficha')),
                ('registro_facial_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.registrofacial')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_objeto', models.CharField(max_length=20)),
                ('modelo_objeto', models.CharField(max_length=20)),
                ('descripcion_objeto', models.TextField(max_length=1000)),
                ('foto_objeto', models.ImageField(blank=True, upload_to='foto_objeto')),
                ('usuario_objeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ingreso', models.DateTimeField(auto_now_add=True)),
                ('datos_biometricos_ingreso', models.ImageField(upload_to='foto_ingreso')),
                ('usuario_ingreso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='ficha',
            name='programa_ficha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.programa'),
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cntEmerg', models.CharField(max_length=50)),
                ('apellido_cntEmerg', models.CharField(max_length=50)),
                ('celular_cntEmerg', models.CharField(max_length=12)),
                ('parentezco_cntEmerg', models.CharField(max_length=30)),
                ('genero_cntEmerg', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20)),
                ('usuario_cntEmerg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.usuario')),
            ],
        ),
    ]
