# Generated by Django 4.1.13 on 2024-07-03 04:39

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='contrasenia_usuario')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='nombres_usuario')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='apellidos_usuario')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo_electronico_usuario')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_documento_usuario', models.CharField(choices=[('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Cedula de ciudadania', 'Cedula de ciudadania'), ('Cedula de extranjeria', 'Cedula de extranjeria')], db_column='tipo_documento_usuario', default='', max_length=50)),
                ('numero_documento_usuario', models.CharField(db_column='numero_documento_usuario', default='', max_length=20, unique=True)),
                ('genero_usuario', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_column='genero_usuario', max_length=20)),
                ('rol_usuario', models.CharField(choices=[('Administrador', 'Administrador'), ('Guardia', 'Guardia'), ('Instructor', 'Instructor'), ('Aprendiz', 'Aprendiz')], db_column='rol_usuario', max_length=13)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_programa', models.CharField(db_column='nombre_programa', max_length=100)),
                ('tipo_formacion_programa', models.CharField(choices=[('Tecnico', 'Tecnico'), ('Tecnologo', 'Tecnologo')], db_column='tipo_formacion_programa', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_biometricos_registro', models.ImageField(db_column='datos_biometricos_registro', upload_to='datos_biometricos_registro')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_hora_registro')),
                ('usuario_registro_facial', models.ForeignKey(db_column='usuario_registro_facial', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_objeto', models.CharField(db_column='marca_objeto', max_length=20)),
                ('modelo_objeto', models.CharField(db_column='modelo_objeto', max_length=20)),
                ('descripcion_objeto', models.TextField(db_column='descripcion_objeto', max_length=1000)),
                ('foto_objeto', models.ImageField(blank=True, db_column='foto_objeto', upload_to='foto_objeto')),
                ('usuario_objeto', models.ForeignKey(db_column='usuario_objeto', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_biometricos_ingreso', models.ImageField(db_column='datos_biometricos_ingreso', upload_to='datos_biometricos_ingreso')),
                ('fecha_hora_ingreso', models.DateTimeField(auto_now_add=True, db_column='fecha_hora_ingreso')),
                ('usuario_ingreso', models.ForeignKey(db_column='usuario_ingreso', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.CharField(db_column='numero_ficha', max_length=20, unique=True)),
                ('aprendices_matriculados_ficha', models.IntegerField(db_column='aprendices_matriculados_ficha')),
                ('aprendices_actuales_ficha', models.IntegerField(db_column='aprendices_actuales_ficha')),
                ('jornada_ficha', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], db_column='jornada_ficha', max_length=50)),
                ('programa_ficha', models.ForeignKey(db_column='programa_ficha', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.programa')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cntEmerg', models.CharField(db_column='nombre_cntEmerg', max_length=50)),
                ('apellido_cntEmerg', models.CharField(db_column='apellido_cntEmerg', max_length=50)),
                ('tipo_documento_cntEmerg', models.CharField(choices=[('Cedula de ciudadania', 'Cedula de ciudadania'), ('Cedula de extranjeria', 'Cedula de extranjeria')], db_column='tipo_documento_cntEmerg', default='', max_length=50)),
                ('numero_documento_cntEmerg', models.CharField(db_column='numero_documento_cntEmerg', default='', max_length=20, unique=True)),
                ('celular_cntEmerg', models.CharField(db_column='celular_cntEmerg', max_length=12)),
                ('genero_cntEmerg', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_column='genero_cntEmerg', max_length=20)),
                ('parentezco_cntEmerg', models.CharField(db_column='parentezco_cntEmerg', max_length=30)),
                ('usuario_cntEmerg', models.ForeignKey(db_column='usuario_cntEmerg', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='ficha_usuario',
            field=models.ForeignKey(db_column='ficha_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.ficha'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
