# Generated by Django 4.1.13 on 2024-07-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_senauthenticator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero_usuario',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_column='genero_usuario', max_length=9),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol_usuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Guardia de seguridad', 'Guardia de seguridad'), ('Funcionario', 'Funcionario'), ('Instructor', 'Instructor'), ('Aprendiz', 'Aprendiz')], db_column='rol_usuario', max_length=20),
        ),
    ]
