# Generated by Django 4.1.13 on 2024-07-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_senauthenticator', '0002_alter_usuario_email_alter_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='tipo_formacion_programa',
            field=models.CharField(choices=[('Tecnologo', 'Tecnologo'), ('Tecnico', 'Tecnico')], db_column='tipo_formacion_programa', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol_usuario',
            field=models.CharField(choices=[('Aprendiz', 'Aprendiz'), ('Instructor', 'Instructor'), ('Administrador', 'Administrador'), ('Funcionario', 'Funcionario'), ('Guardia de seguridad', 'Guardia de seguridad')], db_column='rol_usuario', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento_usuario',
            field=models.CharField(choices=[('Cedula de ciudadania', 'Cedula de ciudadania'), ('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Cedula de extranjeria', 'Cedula de extranjeria')], db_column='tipo_documento_usuario', default='', max_length=50),
        ),
    ]
