# Generated by Django 4.1.13 on 2024-06-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_senauthenticator', '0002_alter_registrofacial_datos_biometricos_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasenia_usuario',
            field=models.CharField(default='default_value', max_length=30),
            preserve_default=False,
        ),
    ]
