# Generated by Django 4.1.13 on 2024-06-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_senauthenticator', '0004_alter_ficha_jornada_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoemergencia',
            name='numero_documento_cntEmerg',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='contactoemergencia',
            name='tipo_documento_cntEmerg',
            field=models.CharField(choices=[('Cedula de ciudadania', 'Cedula de ciudadania'), ('Cedula de extranjeria', 'Cedula de extranjeria')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='datos_biometricos_ingreso',
            field=models.ImageField(upload_to='datos_biometricos_ingreso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento_usuario',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento_usuario',
            field=models.CharField(choices=[('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Cedula de ciudadania', 'Cedula de ciudadania'), ('Cedula de extranjeria', 'Cedula de extranjeria')], default='', max_length=50),
        ),
    ]
