# Generated by Django 4.1.13 on 2024-06-24 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_senauthenticator', '0006_alter_usuario_ficha_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoemergencia',
            name='apellido_cntEmerg',
            field=models.CharField(db_column='apellido_cntEmerg', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactoemergencia',
            name='celular_cntEmerg',
            field=models.CharField(db_column='celular_cntEmerg', max_length=12),
        ),
        migrations.AlterField(
            model_name='contactoemergencia',
            name='genero_cntEmerg',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_column='genero_cntEmerg', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactoemergencia',
            name='nombre_cntEmerg',
            field=models.CharField(db_column='nombre_cntEmerg', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactoemergencia',
            name='numero_documento_cntEmerg',
            field=models.CharField(db_column='numero_documento_cntEmerg', default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='contactoemergencia',
            name='parentezco_cntEmerg',
            field=models.CharField(db_column='parentezco_cntEmerg', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactoemergencia',
            name='tipo_documento_cntEmerg',
            field=models.CharField(choices=[('Cedula de ciudadania', 'Cedula de ciudadania'), ('Cedula de extranjeria', 'Cedula de extranjeria')], db_column='tipo_documento_cntEmerg', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactoemergencia',
            name='usuario_cntEmerg',
            field=models.ForeignKey(db_column='usuario_cntEmerg', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.usuario'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='aprendices_actuales_ficha',
            field=models.IntegerField(db_column='aprendices_actuales_ficha'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='aprendices_matriculados_ficha',
            field=models.IntegerField(db_column='aprendices_matriculados_ficha'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='jornada_ficha',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], db_column='jornada_ficha', max_length=50),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='numero_ficha',
            field=models.CharField(db_column='numero_ficha', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='programa_ficha',
            field=models.ForeignKey(db_column='programa_ficha', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.programa'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='datos_biometricos_ingreso',
            field=models.ImageField(db_column='datos_biometricos_ingreso', upload_to='datos_biometricos_ingreso'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha_hora_ingreso',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_hora_ingreso'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='usuario_ingreso',
            field=models.ForeignKey(db_column='usuario_ingreso', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.usuario'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='descripcion_objeto',
            field=models.TextField(db_column='descripcion_objeto', max_length=1000),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='foto_objeto',
            field=models.ImageField(blank=True, db_column='foto_objeto', upload_to='foto_objeto'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='marca_objeto',
            field=models.CharField(db_column='marca_objeto', max_length=20),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='modelo_objeto',
            field=models.CharField(db_column='modelo_objeto', max_length=20),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='usuario_objeto',
            field=models.ForeignKey(db_column='usuario_objeto', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.usuario'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='nombre_programa',
            field=models.CharField(db_column='nombre_programa', max_length=100),
        ),
        migrations.AlterField(
            model_name='programa',
            name='tipo_formacion_programa',
            field=models.CharField(choices=[('Tecnico', 'Tecnico'), ('Tecnologo', 'Tecnologo')], db_column='tipo_formacion_programa', max_length=30),
        ),
        migrations.AlterField(
            model_name='registrofacial',
            name='datos_biometricos_registro',
            field=models.ImageField(db_column='datos_biometricos_registro', upload_to='datos_biometricos_registro'),
        ),
        migrations.AlterField(
            model_name='registrofacial',
            name='fecha_hora_registro',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_hora_registro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos_usuario',
            field=models.CharField(db_column='apellidos_usuario', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasenia_usuario',
            field=models.CharField(db_column='contrasenia_usuario', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_institucional_usuario',
            field=models.CharField(db_column='correo_institucional_usuario', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_personal_usuario',
            field=models.CharField(db_column='correo_personal_usuario', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero_usuario',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_column='genero_usuario', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(db_column='nombre_usuario', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento_usuario',
            field=models.CharField(db_column='numero_documento_usuario', default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol_usuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Guardia', 'Guardia'), ('Instructor', 'Instructor'), ('Aprendiz', 'Aprendiz')], db_column='rol_usuario', max_length=13),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento_usuario',
            field=models.CharField(choices=[('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Cedula de ciudadania', 'Cedula de ciudadania'), ('Cedula de extranjeria', 'Cedula de extranjeria')], db_column='tipo_documento_usuario', default='', max_length=50),
        ),
    ]
